const OUTPUT_FOLDER_ID = LandGasterId.MFG_OUTPUT_FOLDER_ID();
const OUTPUT_FOLDER_ID_TEST = LandGasterId.MFG_OUTPUT_FOLDER_ID_TEST();
const FOLDER_ID_TO_MAKE_MARKDOWN_DIARY = LandGasterId.MFG_FOLDER_ID_TO_MAKE_MARKDOWN_DIARY();
